version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    environment:
    - discovery.type=single-node
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300
    expose:
    - 9200
    - 9300
    restart: always

  backend:
    build:
      context: scriptor-backend/
    ports:
    - 5000:5000
    expose:
    - 5000
    depends_on:
    - elasticsearch
    environment:
      ES_HOSTS: elasticsearch
    restart: always

volumes:
  esdata: